异步函数
===================

###  Generator 函数
Generator 函数是 ES6 提供的一种异步编程解决方案，封装了多个内部状态。
Generator 函数function关键字与函数名之间有一个星号；函数体内部使用yield表达式，定义不同的内部状态。
```
function* helloWorldGenerator() {
  yield 'hello';
  yield 'world';
  return 'ending';
}
```
调用 Generator 函数后，该函数并不执行，而是返回一个指向内部状态的指针对象，也就是遍历器对象（Iterator Object）。必须调用遍历器对象的next方法，使得指针移向下一个状态。
```
var hw = helloWorldGenerator();
hw.next()
// { value: 'hello', done: false }
hw.next()
// { value: 'world', done: false }
hw.next()
// { value: 'ending', done: true }
hw.next()
// { value: undefined, done: true }
```
函数每次执行到yield就会暂停，yield后面的表达式，只有当调用next方法、内部指针指向该语句时才会执行。

yield表达式本身总是返回undefined。next方法可以带一个参数，该参数就会被当作上一个yield表达式的返回值，通过next方法的参数，可以向函数体内部注入值。
```
function* foo(x) {
  var y = 2 * (yield (x + 1));
  var z = yield (y / 3);
  return (x + y + z);
}

var b = foo(5);
b.next() // { value:6, done:false }
b.next(12) // { value:8, done:false }
b.next(13) // { value:42, done:true }
```

###  async 函数
async 函数就是 Generator 函数的语法糖。
```
function sleep(delay) {
	return new Promise((res,rej) => {
		setTimeout(()=>{
			res(delay)
		}, delay);
	});
}

(async () => {
	let data1 = await sleep(1000);
	console.log(data1); // 1000
	let data2 = await sleep(2000);
	console.log(data2); // 2000
	let data3 = await Promise.all([sleep(1000),sleep(2000)]);
	console.log(data3); // [1000, 2000]
	return data3
})();
```
await命令就是then命令的语法糖，在 Promise 状态变化后，才会接着往下一行代码执行。

```
// 函数声明
async function foo() {}

// 函数表达式
const foo = async function () {};

// 对象的方法
let obj = { async foo() {} };
obj.foo().then(...)

// Class 的方法
class Storage {
  constructor() {
    this.cachePromise = caches.open('avatars');
  }

  async getAvatar(name) {
    const cache = await this.cachePromise;
    return cache.match(`/avatars/${name}.jpg`);
  }
}

const storage = new Storage();
storage.getAvatar('jake').then(…);

// 箭头函数
const foo = async () => {};
```

**状态变化**
async 函数返回一个 Promise 对象。状态类似promise.all()，即所有的await都完成，Promise状态为成功；一个await抛出error，则Promise状态为失败。async 函数函数内的返回值data3会作为then的回调函数参数传递。

**await**
await命令后面需要是一个 Promise 对象，或者有then方法的对象，返回的值是成功的传递值。如果不是，则直接返回对应的值。

**错误处理**
如果await后的promise失败，则会抛出error。因此，async函数自身应该将await的运行放在try...catch内（async函数自身有catch()也能捕获error）。
```
(async () => {
	try {
		await f()
	} catch(err) {

	}
})();
``` 